### ISSUE TITLE
python: can't open file 'C:\\Users\\Admin\\mr.dm\\main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by harshilkabariya18** [Oxlac/MR.DM#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux]

**Additional context**

**Comment by Guhan-SenSam** [comment]
I am unable to understand what is our issue. Can you please format the issue in the suggested way so it will be easier to understand what is your issue and we can work to fix it

**Comment by kitalia** [comment]
try

```
cd src
python3 main.py
```

**Comment by Guhan-SenSam** [comment]
> try
> 
> ```
> cd src
> python3 main.py
> ```
> 
> readme is incorrect: it says you can start main.py from the root but it is actually in src/

Thank you for the answer. I didn't realize i forgot to update the readme. I have changed it now.
